Add support for computed vars
drewmccormack/Forked pull request #15
Opened 2024-12-18 17:35 UTC by Playrom

This PR fix the issues #14, and some unit tests are provided

An unresolved problem is the tabbing of the first lines in the expanded merging function, but it is not related to the issue, and It has not been yet found as an issue because no unit test where provided until this PR for checking the expansion of a property inside @ForkedModel that do not have an attached "@Merge" macro

(ex.)

2024-12-18 22:07 UTC, drewmccormack requested changes
Thank you for the PR! It looks like a nice improvement. 

I've made a bunch of requests, mostly about clarifying the code.

2024-12-18 22:07 UTC, drewmccormack commented on Sources/ForkedModelMacros/VariableDeclSyntaxExtensions.swift
> +        // If no accessors, no reason to check
Just a small thing, but prefer to have empty line before these two comments, to space out a little.

2024-12-18 22:07 UTC, drewmccormack commented on Sources/ForkedModelMacros/VariableDeclSyntaxExtensions.swift
> +        // For every accessors list check if at least one set is present otherwise return nil
Don't understand this comment completely. So the rules for a computed variable are:

- there are accessors
- there is no setter accessor

If that is it, probably should state it clearly. 

I also think the guards here are difficult to follow. Perhaps it is better to add some local variables to show exactly what we are testing.

Could you just write it like this?

```
return accessors.contains { decl in 
    switch decl {
        case .getter:
            return true
        case .accessors(let declList):
            return !declList.contains { $0.accessorSpecifier == .keyword(.set) }
    }
} 
```

I'm actually not sure even this is OK. Is a "didSet" also an accessor in the list? Maybe that is something different. In any case, a clear explanation of what we are trying to find would be good.

2024-12-18 22:07 UTC, drewmccormack commented on Sources/ForkedModelMacros/VariableDeclSyntaxExtensions.swift
> +                // It is get only
I would leave this comment out. It is very obvious from the code here.

2024-12-18 22:07 UTC, drewmccormack commented on Tests/ForkedTests/ForkedModelMacros.swift
> +                    if areEqualForForked(self.text, commonAncestor.text) {
I just merged something that would break this test. Just use == instead of areEqualForForked now.

2024-12-18 22:07 UTC, drewmccormack commented on Tests/ForkedTests/ForkedModelMacros.swift
> +    func testVars() {
What is this testing exactly? Could be a better name.

2024-12-18 22:07 UTC, drewmccormack commented on Tests/ForkedTests/ForkedModelMacros.swift
> +                    if areEqualForForked(self.text, commonAncestor.text) {
Same comment about ==. This will be broken with latest code.

2024-12-18 22:07 UTC, drewmccormack commented on Tests/ForkedTests/ForkedModelMacros.swift
> +                    if areEqualForForked(self.text, commonAncestor.text) {
And again.

2024-12-18 22:07 UTC, drewmccormack commented on Tests/ForkedTests/ForkedModelMacros.swift
> +    }
Can you write a test or two for when it is not a computed property, but has, eg, a didSet?

2024-12-18 22:07 UTC, drewmccormack commented on Sources/ForkedModelMacros/ForkedModelMacro.swift
> +            guard let varSyntax = member.decl.as(VariableDeclSyntax.self), varSyntax.isMerged(), !varSyntax.isComputedVar()
Maybe rename `isComputedVar` to `isComputed`, to match `isMerged` naming scheme.

2024-12-19 08:54 UTC, Playrom commented
I've made the improvements! sorry for the initial PR, I'm not so used to working in open source and I rushed it! 

I think the solution is now more robust

2024-12-19 09:03 UTC, Playrom commented
FYI, Swift Evolution is considering [changing the accessors system ](https://forums.swift.org/t/prospective-vision-accessors/76707/7) , but those changes are still too far in the future, so I would not consider them in this PR

Still, in the future the algorithm to find "which accessor" define the availability of a "setter" may change (even if I think forked will never be used with the low level memory access that those new accessors are for...)

2024-12-19 10:17 UTC, drewmccormack approved these changes
Looks great! Thanks!

2024-12-19 10:17 UTC, merged